package controller;

public enum DeckMenuMessage {
    INVALID_COMMAND,
    NAVIGATION_NOT_POSSIBLE,
    DECK_CREATED,
    DECK_NAME_EXISTS,
    DECK_DELETED,
    NO_DECK_EXISTS,
    DECK_ACTIVATED,
    CARD_ADDED,
    NO_CARD_EXISTS,
    DECK_IS_FULL,
    ALREADY_THREE_CARDS,
    CARD_REMOVED
}
