package controller;

enum MainMenuMessage {
    INVALID_COMMAND,
    LOGGED_OUT,
    NO_PLAYER_EXISTS,
    NO_ACTIVE_DECK_1,
    NO_ACTIVE_DECK_2,
    INVALID_DECK_1,
    INVALID_DECK_2,
    INVALID_ROUND,
    GAME_STARTED_SUCCESSFULLY
}
