package model.effect;

public enum Event {
    YOU_FLIP_SUMMONED_MANUALLY,
    YOU_DESTROYED_BY_ATTACK,
    YOU_DESTROYED_WHILE_ATTACKING,
    DECLARE_ATTACK,
    MONSTER_SUMMONED,
    MONSTER_WITH_1000_ATTACK_SUMMONED,
    ACTIVATE_EFFECT,
    DISABLE_FIELD_SPELL,
    CHECK_FIELD_SPELL,
    QUICK_ACTIVATE
}
